### PR TITLE
bootstrap.sh: the master version should use autoproj from master

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
There is no master/stable version in buildconf, everyone bootstraps either a tag (for a rock release) or master.

**Comment by goldhoorn** [comment]
Jep, and 'master' should use the bootstrap from master.
the releases from stable...

On 21.10.2015 18:57, Sylvain Joyeux wrote:
>
> There is no master/stable version in buildconf, everyone bootstraps
> either a tag (for a rock release) or master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/buildconf/pull/5#issuecomment-149961423>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
> Jep, and 'master' should use the bootstrap from master.

Absolutely not given that the 'stable' flavor is bootstrapped using the 'master' buildconf. Autoproj is such a critical component, I really want people to use the master version on purpose, not by accident.

**Comment by goldhoorn** [comment]
Your right i mixed there something with the whole releases tags vs.
flavors.. agree to keep stable here...

i close

On 22.10.2015 13:16, Sylvain Joyeux wrote:
>
>     Jep, and 'master' should use the bootstrap from master.
>
> Absolutely not given that the 'stable' flavor is bootstrapped using
> the 'master' buildconf. Autoproj is such a critical component, I
> really want people to use the master version on purpose, not by accident.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/buildconf/pull/5#issuecomment-150183822>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Pull request closed without merging**
