### PR TITLE
Adapted bootstrap.sh script for ruby2.0 and reject usage of 1.9

### PR DESCRIPTION
**Pull request by goldhoorn**
This should merged asap

### CODE REVIEW

**Comment by goldhoorn** [comment]
Btw. 
why do we have this bootstrap.sh scripts at all i dont like them. 
They are copied around, and from a maintainer sight we have no way to adapt them.
The branch settings get more complex. Why we not simply tell the customers howto bootstrap with using the autoproj_bootstrap script and removing this file at all?

**Comment by goldhoorn** [comment]
...however we decide we should merge this for now...

**Comment by doudou** [comment]
> why do we have this bootstrap.sh scripts at all i dont like them. 

Actually, this very situation is why we want them. By changing the bootstrap.sh script we make sure that people transparently know that they should update to ruby 2.0 *before* bootstrapping autoproj instead of getting the error when rock.core is loaded.

**Comment by goldhoorn** [comment]
Then :+1:  for apply this on 10.06.2015 as announced

**Comment by goldhoorn** [comment]
ops i mean this is a patch which should applied before, since there are no comments on the patch itself i merge

**Pull request merged**
